### ISSUE TITLE
osm4routing_xml missing

### ISSUE THREAD

**Issue by danst0** [Tristramg/osm4routing#23]
Hi,

I get an error that the file osm4routing_xml.py is missing.

Any hints?

Daniel

**Comment by Tristramg** [comment]
Hey, sorry about that.

It seems that it didn’t correctly generated the C++/python bindings during the build process.

However, this project is deprecated for many years. Have a look at https://github.com/Tristramg/osm4routing2. It isn’t great either, but the design isn’t as stupid as the one I did on this prototype.

**Comment by danst0** [comment]
Makes sense. Thanks for the great project!
